name: Render README

concurrency:
  group: "README"
  cancel-in-progress: true

on:
  push:
    paths: 
      - README.qmd

jobs:
  quarto:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render using Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: README.qmd
      
      - name: Commit results
        run: |
          git config --global user.name 'rmtrane'
          git config --global user.email 'rmtrane@gmail.com'
          git add README.md
          git commit -m "Re-build README.qmd on push" || echo "No changes to commit"
          git push origin || echo "No changes to commit"